### ISSUE TITLE
Think of how to do loyalty points system

### ISSUE THREAD

**Issue by vidun-jay** [vidun-jay/3005-group-project#16]

**Comment by tyrada** [comment]
- add a set amount of points for personal classes (ex 100 for group and 200 for personal?) maybe change that ratio a bit to accommodate prices
- or we can go a different route and do 100 points for every dollar spent and charge personal classes more than group (easiest option to implement, I feel like)
- also for time? If you have been a member for a year you get x points. (harder to do and check)
